FROM nvidia/cuda:12.2.0-devel-ubuntu22.04
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y python3 python3-pip git gcc

WORKDIR /launch

COPY requirements.txt ./
RUN pip install -r requirements.txt

RUN git clone https://github.com/dkphd/GP_Ensembling.git

RUN pip install ./GP_Ensembling
COPY inference.py ./
COPY ./src ./src
COPY ./metadata ./metadata


CMD python3 inference.py